[versions]
dokka = "2.1.0"
spek = "2.0.19"
gradleUtils = "1.2.2"
okhttp = "4.12.0"
jackson = "2.20.1"
# No need to keep the same Kotlin version with Gradle, at least because kotlin runtime is a transitive dependency of okhttp
kotlin = "2.2.20"
junit = "6.0.2"

[libraries]
snakeyaml = "org.yaml:snakeyaml:2.5"
assertk = "com.willowtreeapps.assertk:assertk-jvm:0.28.1"
# version 1.13.8 doesn't work because of JVM 11 bytecode despite of https://github.com/mockk/mockk/pull/1161
mockk = "io.mockk:mockk:1.14.7"
tabbedCodeExtension = "com.bmuschko:asciidoctorj-tabbed-code-extension:0.3"
orgJson = "org.json:json:20251224"
jsonPath = "com.jayway.jsonpath:json-path:2.10.0"
kotestAssertions = "io.kotest:kotest-assertions-core:6.0.7"
jacksonDataBind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jacksonDataFormatYaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okHttpTls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttp" }
okHttpMockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
io-github-build-extensions-oss-gradle-plugin-utils = { module = "io.github.build-extensions-oss:gradle-plugin-utils", version.ref = "gradleUtils" }
io-github-build-extensions-oss-gradle-plugin-test-utils = { module = "io.github.build-extensions-oss:gradle-plugin-test-utils", version.ref = "gradleUtils" }
spekDsl = { module = "org.spekframework.spek2:spek-dsl-jvm", version.ref = "spek" }
spekRunner = { module = "org.spekframework.spek2:spek-runner-junit5", version.ref = "spek" }
junitEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
# is needed because of https://github.com/gradle/gradle/issues/34512#issuecomment-3149703490
junitPlatform = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

org-jetbrains-kotlinx-kover = { module = "org.jetbrains.kotlinx:kover-gradle-plugin", version = "0.9.4" }
org-jetbrains-kotlin-kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
org-jetbrains-dokka-org-jetbrains-dokka-gradle-plugin = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
org-jetbrains-dokka-javadoc-org-jetbrains-dokka-javadoc-gradle-plugin = { module = "org.jetbrains.dokka-javadoc:org.jetbrains.dokka-javadoc.gradle.plugin", version.ref = "dokka" }

# https://github.com/detekt/detekt
# It must be compatible with Kotlin version, therefore it must be also compatible with Gradle (we use the version of the embedded Kotlin)
# See https://detekt.dev/docs/introduction/compatibility/
io-gitlab-arturbosch-detekt-detekt-gradle-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.23.8" }


[plugins]
gradlePublish = { id = "com.gradle.plugin-publish", version = "2.0.0" }
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.5" }
benManesVersions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }

